-- 코드를 입력하세요
WITH CHECK_A AS (
    SELECT * FROM FIRST_HALF AS FH
    WHERE FH.TOTAL_ORDER > 3000
)
SELECT A.FLAVOR
FROM CHECK_A A INNER JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC;